package io.github.xiaokun19.hashlite.core

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * 校验文件解析/生成。
 *
 * 样本都取自真实工具的产出形态：`sha256sum`（coreutils）、macOS `shasum`/BSD、
 * 老式 `.sfv` 工具（`;` 注释 + 大写十六进制）。
 */
class ChecksumFileTest {

    private val sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    private val md5 = "d41d8cd98f00b204e9800998ecf8427e"
    private val sha512 = "b".repeat(128)
    private val crc32 = "352441c2"

    // ------------------------------------------------------------ coreutils

    @Test
    fun `coreutils lines are parsed including binary marker`() {
        val text = """
            $md5  empty.bin
            $sha256 *binary.bin
            ${sha256.uppercase()}   spaced.txt
        """.trimIndent()

        val list = ChecksumFile.parse(text, "checksums.sha256")
        assertEquals(3, list.entries.size)
        assertEquals(ChecksumFormat.COREUTILS, list.format)
        assertTrue(list.badLines.isEmpty())

        assertEquals("empty.bin", list.entries[0].name)
        assertEquals(LiteAlgorithm.MD5, list.entries[0].algorithm)
        assertEquals(md5, list.entries[0].hash)

        assertEquals("binary.bin", list.entries[1].name)
        assertEquals(LiteAlgorithm.SHA256, list.entries[1].algorithm)

        // 大写十六进制一律折成小写存储，比对时才不会被大小写坑到
        assertEquals(sha256, list.entries[2].hash)
        assertEquals("spaced.txt", list.entries[2].name)
    }

    @Test
    fun `coreutils escaped file names are unescaped`() {
        // 文件名里有换行时 GNU 会转义、并在行首加一个反斜杠
        val text = "\\$sha256  a\\nb.bin"
        val list = ChecksumFile.parse(text, "checksums.sha256")
        assertEquals(1, list.entries.size)
        assertEquals("a\nb.bin", list.entries[0].name)
    }

    // ------------------------------------------------------------ BSD

    @Test
    fun `bsd lines are parsed with and without spaces`() {
        val text = """
            SHA256 (archive.tar.gz) = $sha256
            MD5(short.bin) = ${md5.uppercase()}
        """.trimIndent()

        val list = ChecksumFile.parse(text, "checksums")
        assertEquals(2, list.entries.size)
        assertEquals(ChecksumFormat.BSD, list.format)
        assertEquals(LiteAlgorithm.SHA256, list.entries[0].algorithm)
        assertEquals("archive.tar.gz", list.entries[0].name)
        assertEquals(LiteAlgorithm.MD5, list.entries[1].algorithm)
        assertEquals(md5, list.entries[1].hash)
    }

    // ------------------------------------------------------------ SFV

    @Test
    fun `sfv lines are parsed with comments and uppercase crc`() {
        val text = """
            ; SFV checksum file
            a.bin ABCD1234
            b.bin abcd1234 ; trailing comment
        """.trimIndent()

        val list = ChecksumFile.parse(text, "checksums.sfv")
        assertEquals(2, list.entries.size)
        assertEquals(ChecksumFormat.SFV, list.format)
        assertEquals(LiteAlgorithm.CRC32, list.entries[0].algorithm)
        assertEquals("abcd1234", list.entries[0].hash)
        assertEquals("b.bin", list.entries[1].name)
    }

    @Test
    fun `sfv shaped lines are recognized even without the extension hint`() {
        val list = ChecksumFile.parse("movie.mkv $crc32\n", null)
        assertEquals(1, list.entries.size)
        assertEquals(LiteAlgorithm.CRC32, list.entries[0].algorithm)
        assertEquals("movie.mkv", list.entries[0].name)
    }

    // ------------------------------------------------------------ 消歧与容错

    @Test
    fun `hex length ambiguity is resolved by the file name hint`() {
        assertEquals(
            LiteAlgorithm.SHA256,
            ChecksumFile.parse("$sha256  x.bin", "checksums.sha256").entries[0].algorithm,
        )
        assertEquals(
            LiteAlgorithm.SHA3_256,
            ChecksumFile.parse("$sha256  x.bin", "checksums.sha3-256").entries[0].algorithm,
        )
        assertEquals(
            LiteAlgorithm.SM3,
            ChecksumFile.parse("$sha256  x.bin", "checksums.sm3").entries[0].algorithm,
        )
        assertEquals(
            LiteAlgorithm.SHA512,
            ChecksumFile.parse("$sha512  x.bin", null).entries[0].algorithm,
        )
    }

    @Test
    fun `comments blank lines and garbage do not invalidate the list`() {
        val text = """
            # generated by sha256sum

            $sha256  good.bin
            this line makes no sense
        """.trimIndent()

        val list = ChecksumFile.parse(text, "checksums.sha256")
        assertEquals(1, list.entries.size)
        assertEquals("good.bin", list.entries[0].name)
        assertEquals(1, list.badLines.size)
        assertTrue(list.badLines[0].startsWith("this line"))
    }

    @Test
    fun `unknown hash length keeps the entry but flags it`() {
        val list = ChecksumFile.parse("abcdefabcdeffile.bin\n", null)
        // 14 位十六进制：不是任何已知算法，但那行仍在（界面能提示"这行认不出算法"）
        assertTrue(list.entries.isEmpty() || list.entries[0].algorithm == null)
        assertTrue(list.hasUnknownAlgorithm || list.badLines.isNotEmpty())
    }

    // ------------------------------------------------------------ 查找与缺失

    @Test
    fun `lookup falls back to the bare file name`() {
        val list = ChecksumFile.parse("$sha256  sub/dir/a.bin\n", "checksums.sha256")
        assertNotNull(list.lookup("sub/dir/a.bin"))
        assertNotNull(list.lookup("a.bin"))
        assertNotNull(list.lookup("./sub/dir/a.bin"))
        // Windows 写出来的反斜杠路径也能对上
        assertNotNull(list.lookup("SUB\\DIR\\A.BIN"))
        assertNull(list.lookup("other.bin"))
    }

    @Test
    fun `missing reports entries without files`() {
        val list = ChecksumFile.parse(
            """
            $sha256  a.bin
            $sha256  dir/b.bin
            $sha256  gone.bin
            """.trimIndent(),
            "checksums.sha256",
        )
        val missing = list.missing(listOf("a.bin", "dir/b.bin", "extra.bin"))
        assertEquals(listOf("gone.bin"), missing.map { it.name })
        assertTrue(list.missing(listOf("a.bin", "b.bin", "gone.bin")).isEmpty())
    }

    // ------------------------------------------------------------ 生成

    @Test
    fun `build round trips through every format`() {
        // 同一份清单里必须用同一种算法，否则 parsed.algorithm（"整表统一算法"）本来就是 null
        val coreutilsLines = listOf(
            ChecksumFile.ChecksumLine("a.bin", sha256),
            ChecksumFile.ChecksumLine("sub/b.bin", sha256),
        )
        val sfvLines = listOf(
            ChecksumFile.ChecksumLine("a.bin", crc32),
            ChecksumFile.ChecksumLine("sub/b.bin", "0badc0de"),
        )

        for (format in ChecksumFormat.entries) {
            val algorithm = if (format == ChecksumFormat.SFV) LiteAlgorithm.CRC32 else LiteAlgorithm.SHA256
            val lines = if (format == ChecksumFormat.SFV) sfvLines else coreutilsLines
            val text = ChecksumFile.build(lines, algorithm, format)
            val hint = ChecksumFile.suggestFileName(null, algorithm, format)
            val parsed = ChecksumFile.parse(text, hint)

            assertEquals("$format 行数", lines.size, parsed.entries.size)
            assertEquals("$format 算法", algorithm, parsed.algorithm)
            assertEquals("$format 格式", format, parsed.format)
            assertEquals(lines.map { it.name }, parsed.entries.map { it.name })
            assertEquals(lines.map { it.hex.lowercase() }, parsed.entries.map { it.hash })
        }
    }

    @Test
    fun `build escapes newlines the way coreutils does`() {
        val text = ChecksumFile.build(
            listOf(ChecksumFile.ChecksumLine("a\nb.bin", sha256)),
            LiteAlgorithm.SHA256,
            ChecksumFormat.COREUTILS,
        )
        assertTrue(text.startsWith("\\"))
        assertTrue(text.contains("a\\nb.bin"))
        assertEquals("a\nb.bin", ChecksumFile.parse(text, "checksums.sha256").entries[0].name)
    }

    @Test
    fun `sfv output uses uppercase crc`() {
        val text = ChecksumFile.build(
            listOf(ChecksumFile.ChecksumLine("a.bin", crc32)),
            LiteAlgorithm.CRC32,
            ChecksumFormat.SFV,
        )
        assertTrue(text.contains("a.bin ${crc32.uppercase()}"))
    }

    // ------------------------------------------------------------ 命名辅助

    @Test
    fun `suggested file names follow the usual conventions`() {
        assertEquals("Download.sha256", ChecksumFile.suggestFileName("Download", LiteAlgorithm.SHA256, ChecksumFormat.COREUTILS))
        assertEquals("rom.zip.sha512", ChecksumFile.suggestFileName("/sdcard/rom.zip", LiteAlgorithm.SHA512, ChecksumFormat.COREUTILS))
        assertEquals("checksums.sfv", ChecksumFile.suggestFileName(null, LiteAlgorithm.CRC32, ChecksumFormat.SFV))
        assertEquals("mod.sha3-256", ChecksumFile.suggestFileName("mod", LiteAlgorithm.SHA3_256, ChecksumFormat.COREUTILS))
    }

    @Test
    fun `algorithm and format are inferred from common file names`() {
        assertEquals(LiteAlgorithm.SHA256, ChecksumFile.algorithmFromFileName("SHA256SUMS"))
        assertEquals(LiteAlgorithm.SHA256, ChecksumFile.algorithmFromFileName("foo.sha256"))
        assertEquals(LiteAlgorithm.MD5, ChecksumFile.algorithmFromFileName("md5sum.txt"))
        assertEquals(LiteAlgorithm.SHA3_256, ChecksumFile.algorithmFromFileName("checksums.sha3-256.txt"))
        assertEquals(LiteAlgorithm.CRC32, ChecksumFile.algorithmFromFileName("data.sfv"))
        assertNull(ChecksumFile.algorithmFromFileName("readme.txt"))

        assertEquals(ChecksumFormat.SFV, ChecksumFile.formatFromFileName("data.sfv"))
        assertEquals(ChecksumFormat.COREUTILS, ChecksumFile.formatFromFileName("data.sha256"))
        assertEquals(ChecksumFormat.COREUTILS, ChecksumFile.formatFromFileName("SHA256SUMS"))
        assertNull(ChecksumFile.formatFromFileName("data.bin"))
    }

    @Test
    fun `hashes are compared case insensitively`() {
        val list = ChecksumFile.parse("${sha256.uppercase()}  a.bin\n", "checksums.sha256")
        assertEquals(sha256, list.lookup("a.bin")?.hash)
        assertFalse(list.entries[0].hash.contains("E") || list.entries[0].hash.contains("F"))
    }
}